//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIPIT_11.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Moving
    {
        public int id { get; set; }
        public int exhibit_fk { get; set; }
        public int halls_fk { get; set; }
        public System.DateTime date_start { get; set; }
        public System.DateTime date_end { get; set; }
    
        public virtual Exhibits Exhibits { get; set; }
        public virtual Halls Halls { get; set; }
    }
}
