//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client5.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTex_obslysh", ReplyAction="http://tempuri.org/IService1/GetTex_obslyshResponse")]
        System.Data.DataSet GetTex_obslysh();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTex_obslysh", ReplyAction="http://tempuri.org/IService1/GetTex_obslyshResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetTex_obslyshAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Insert", ReplyAction="http://tempuri.org/IService1/InsertResponse")]
        void Insert(string d1, string d2, string d3);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Insert", ReplyAction="http://tempuri.org/IService1/InsertResponse")]
        System.Threading.Tasks.Task InsertAsync(string d1, string d2, string d3);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Client5.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Client5.ServiceReference1.IService1>, Client5.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet GetTex_obslysh() {
            return base.Channel.GetTex_obslysh();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetTex_obslyshAsync() {
            return base.Channel.GetTex_obslyshAsync();
        }
        
        public void Insert(string d1, string d2, string d3) {
            base.Channel.Insert(d1, d2, d3);
        }
        
        public System.Threading.Tasks.Task InsertAsync(string d1, string d2, string d3) {
            return base.Channel.InsertAsync(d1, d2, d3);
        }
    }
}
